---
title: "Portfolio"
site: distill::distill_website
---

##GV300 Progress

This is what I have been doing in my previous assignments. Below you will see that I will load the packages needed for the code, as well as the codes that will be essential for the display of the data visualisation. 


```{r setup, eval=TRUE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 5
)

install.packages(c("tidyverse", "ggplot2", "patchwork"))

library(tidyverse)
library(ggplot2)
library(patchwork)

```

```{r first, eval=TRUE}
uk_csv <- "https://electionresults.parliament.uk/general-elections/6/candidacies.csv"
uk_raw <- readr::read_csv(uk_csv, show_col_types = FALSE)
names(uk_raw) <- names(uk_raw) %>% tolower() %>% str_replace_all("\\s+", "_")
```


```{r cleaning, eval=TRUE}
uk1 <- uk_raw %>%
  filter(!`election_is_by-election`)

uk2 <- uk1 %>%
  select(
    constituency = constituency_name,
    country      = country_name,
    valid_votes  = candidate_vote_count,
    electorate   = electorate
  )

uk3 <- uk2 %>%
  group_by(country, constituency) %>%
  summarise(
    valid_votes = sum(valid_votes, na.rm = TRUE),
    electorate  = max(electorate, na.rm = TRUE),
    .groups = "drop"
  )

uk <- uk3 %>%
  mutate(turnout_registered = 100 * valid_votes / electorate) %>%
  filter(is.finite(turnout_registered), electorate > 0)

glimpse(uk)
```


```{r plot1, eval=TRUE}
overall_mean <- mean(uk$valid_votes)

ggplot(uk, aes(x = valid_votes)) +
  geom_histogram(bins = 25, fill = "#008080", colour = "black", alpha = 0.7) +
  geom_vline(xintercept = overall_mean, 
             color = "#FF2050", linetype = "dashed", linewidth = 1) +
  facet_wrap(~ country, ncol = 2) +
  labs(
    title = "Distribution of Constituency Sizes by Country",
    subtitle = "Red line shows overall UK mean",
    x = "Number of Valid Votes",
    y = "Count of Constituencies"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    strip.text = element_text(face = "bold")
  )

```

